subinfo_fields:
- name: subject_id
  type: int
  constraints:
    min: 101
    max: 999
    digits: 3
subinfo_mapping:
  subject_id: Subject ID (3 digits)
  Participant Information: Participant Information
  registration_failed: Registration failed
  registration_successful: Registration successful
  invalid_input: '{field} is invalid'
window:
  size:
  - 1280
  - 720
  units: pix
  screen: 0
  bg_color: black
  fullscreen: false
task:
  task_name: cyberball
  save_path: ./outputs/qa
  total_blocks: 1
  total_trials: 8
  trial_per_block: 8
  conditions:
  - inclusion
  key_list:
  - f
  - j
  - space
  left_key: f
  right_key: j
  no_response_policy: left
  language: English
  voice_name: en-US-AriaNeural
  voice_enabled: false
timing:
  avatar_decision_delay:
  - 0.05
  - 0.08
  toss_animation_duration: 0.05
  participant_timeout: 0.45
  inter_toss_interval: 0.02
stimuli:
  instruction_text:
    type: text
    text: Cyberball QA
    color: white
    height: 30
    wrapWidth: 980
    pos:
    - 0
    - 40
  participant_node:
    type: circle
    radius: 58
    pos:
    - 0
    - -245
    fillColor:
    - 0.15
    - 0.32
    - 0.74
    lineColor: white
    lineWidth: 3
  left_node:
    type: circle
    radius: 58
    pos:
    - -335
    - 180
    fillColor:
    - 0.45
    - 0.45
    - 0.45
    lineColor: white
    lineWidth: 3
  right_node:
    type: circle
    radius: 58
    pos:
    - 335
    - 180
    fillColor:
    - 0.45
    - 0.45
    - 0.45
    lineColor: white
    lineWidth: 3
  participant_label:
    type: text
    text: You
    color: white
    height: 26
    pos:
    - 0
    - -245
  left_label:
    type: text
    text: Player A
    color: white
    height: 24
    pos:
    - -335
    - 180
  right_label:
    type: text
    text: Player B
    color: white
    height: 24
    pos:
    - 335
    - 180
  ball:
    type: circle
    radius: 18
    fillColor: yellow
    lineColor: black
    lineWidth: 2
    pos:
    - -335
    - 180
  avatar_wait_prompt:
    type: text
    text: '{holder_name} is deciding...'
    color:
    - 0.82
    - 0.82
    - 0.82
    height: 24
    pos:
    - 0
    - -40
    wrapWidth: 900
  participant_prompt:
    type: text
    text: 'Ball target: F = Player A, J = Player B'
    color:
    - 0.95
    - 0.95
    - 0.95
    height: 26
    pos:
    - 0
    - -45
    wrapWidth: 900
  status_line:
    type: text
    text: '{condition_name} | Toss {toss_num}/{total_tosses}'
    color:
    - 0.75
    - 0.75
    - 0.75
    height: 22
    pos:
    - 0
    - 300
    wrapWidth: 900
  block_break:
    type: text
    text: 'Block {block_num}/{total_blocks}

      Receives: {participant_receives}
      Turns: {participant_turns}


      Press SPACE'
    color: white
    height: 26
    wrapWidth: 980
  good_bye:
    type: text
    text: 'QA complete.

      Tosses: {total_tosses}
      Receives: {participant_receives_total}


      Press SPACE to exit.'
    color: white
    height: 28
    wrapWidth: 980
triggers:
  map:
    exp_onset: 1
    exp_end: 2
    block_onset: 10
    block_end: 11
    avatar_turn_onset: 20
    participant_turn_onset: 30
    participant_choice_left: 31
    participant_choice_right: 32
    participant_timeout: 33
    toss_start_to_participant: 40
    toss_start_to_left: 41
    toss_start_to_right: 42
    toss_end: 43
  driver:
    type: serial_url
    url: loop://
    baudrate: 115200
  timing:
    post_delay_ms: 1
  policy:
    strict: false
controller:
  inclusion_receive_prob: 0.33
  exclusion_initial_receives: 2
  random_seed: 0
  enable_logging: true
qa:
  output_dir: outputs/qa
  timing_scale: 1.0
  acceptance_criteria:
    required_columns:
    - condition
    - trial_id
    - from_player
    - to_player
    - participant_turn
    - participant_response
    - participant_received
    expected_trial_count: 8
    triggers_required: true
